// Copyright (c) 2026 Lifelike & Believable Animation Design, Inc. | Athomas Goldberg. All Rights Reserved.
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS

#include "Interfaces/IPluginManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "VRMSpringBonesParser.h"
#include "VRMSpringBonesTypes.h"

namespace VRMFixtures
{
	/** Plugins/VRMInterchange/Tests/Fixtures (generated by scripts/make_vrm_fixtures.py). */
	static FString GetFixtureDir()
	{
		const TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("VRMInterchange"));
		return Plugin.IsValid() ? FPaths::Combine(Plugin->GetBaseDir(), TEXT("Tests"), TEXT("Fixtures")) : FString();
	}

	static const TCHAR* const Names[] = {
		TEXT("vrm0_minimal"),
		TEXT("vrm1_minimal"),
		TEXT("multi_skin"),
		TEXT("rigid_accessory"),
		TEXT("unnamed_and_duplicate_nodes"),
		TEXT("armature_transform"),
		TEXT("bind_pose_offset"),
	};
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FVRMFixturesAvailable, "VRM.Fixtures.Available",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FVRMFixturesAvailable::RunTest(const FString& Parameters)
{
	const FString Dir = VRMFixtures::GetFixtureDir();
	if (!TestFalse(TEXT("VRMInterchange plugin found"), Dir.IsEmpty()))
	{
		return false;
	}

	for (const TCHAR* Name : VRMFixtures::Names)
	{
		const FString VrmPath = FPaths::Combine(Dir, FString(Name) + TEXT(".vrm"));
		const FString ExpectedPath = FPaths::Combine(Dir, FString(Name) + TEXT(".expected.json"));
		TestTrue(FString::Printf(TEXT("%s.vrm exists"), Name), FPaths::FileExists(VrmPath));

		FString ExpectedText;
		TSharedPtr<FJsonObject> Expected;
		const bool bLoaded = FFileHelper::LoadFileToString(ExpectedText, *ExpectedPath)
			&& FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(ExpectedText), Expected)
			&& Expected.IsValid();
		TestTrue(FString::Printf(TEXT("%s.expected.json loads"), Name), bLoaded);
	}
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FVRMFixturesSpringSpecDetected, "VRM.Fixtures.SpringSpecDetected",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FVRMFixturesSpringSpecDetected::RunTest(const FString& Parameters)
{
	const FString Dir = VRMFixtures::GetFixtureDir();

	FVRMSpringConfig Config0;
	FString Error;
	TestTrue(TEXT("vrm0_minimal spring data parses"),
		VRM::ParseSpringBonesFromFile(FPaths::Combine(Dir, TEXT("vrm0_minimal.vrm")), Config0, Error));
	TestEqual(TEXT("vrm0_minimal detected as VRM 0.x"), Config0.Spec, EVRMSpringSpec::VRM0);

	FVRMSpringConfig Config1;
	TestTrue(TEXT("vrm1_minimal spring data parses"),
		VRM::ParseSpringBonesFromFile(FPaths::Combine(Dir, TEXT("vrm1_minimal.vrm")), Config1, Error));
	TestEqual(TEXT("vrm1_minimal detected as VRM 1.0"), Config1.Spec, EVRMSpringSpec::VRM1);
	TestEqual(TEXT("vrm1_minimal has one spring"), Config1.Springs.Num(), 1);
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FVRMFixturesSpringJointParameters, "VRM.Fixtures.SpringJointParameters",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FVRMFixturesSpringJointParameters::RunTest(const FString& Parameters)
{
	// Each joint's parameters must match the sidecar's springs.joint_params (glTF units), keyed by
	// node. vrm1_minimal sets different values on every joint of its chain; vrm0_minimal gives
	// every joint its bone group's values.
	const FString Dir = VRMFixtures::GetFixtureDir();
	const float Tolerance = 1.0e-3f;
	const TCHAR* const SpringFixtures[] = { TEXT("vrm1_minimal"), TEXT("vrm0_minimal") };
	for (const TCHAR* Name : SpringFixtures)
	{
		FVRMSpringConfig Config;
		FString Error;
		FString ExpectedText;
		TSharedPtr<FJsonObject> Expected;
		if (!TestTrue(FString::Printf(TEXT("%s parses"), Name), VRM::ParseSpringBonesFromFile(FPaths::Combine(Dir, FString(Name) + TEXT(".vrm")), Config, Error))
			|| !TestTrue(FString::Printf(TEXT("%s sidecar loads"), Name),
				FFileHelper::LoadFileToString(ExpectedText, *FPaths::Combine(Dir, FString(Name) + TEXT(".expected.json")))
				&& FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(ExpectedText), Expected) && Expected.IsValid()))
		{
			continue;
		}

		const TSharedPtr<FJsonObject>* Springs = nullptr;
		const TSharedPtr<FJsonObject>* JointParams = nullptr;
		if (!TestTrue(TEXT("Sidecar has springs.joint_params"), Expected->TryGetObjectField(TEXT("springs"), Springs) && Springs
			&& (*Springs)->TryGetObjectField(TEXT("joint_params"), JointParams) && JointParams))
		{
			continue;
		}

		TestTrue(FString::Printf(TEXT("%s has joints"), Name), Config.Joints.Num() > 0);
		for (const FVRMSpringJoint& Joint : Config.Joints)
		{
			const TSharedPtr<FJsonObject>* Want = nullptr;
			if (!TestTrue(FString::Printf(TEXT("%s joint node %d is in the sidecar"), Name, Joint.NodeIndex),
				(*JointParams)->TryGetObjectField(FString::FromInt(Joint.NodeIndex), Want) && Want))
			{
				continue;
			}
			const FString What = FString::Printf(TEXT("%s node %d"), Name, Joint.NodeIndex);
			TestEqual(*(What + TEXT(" stiffness")), Joint.Stiffness, float((*Want)->GetNumberField(TEXT("stiffness"))), Tolerance);
			TestEqual(*(What + TEXT(" drag")), Joint.Drag, float((*Want)->GetNumberField(TEXT("drag"))), Tolerance);
			TestEqual(*(What + TEXT(" gravity power (UE units)")), Joint.GravityPower, float((*Want)->GetNumberField(TEXT("gravity_power")) * 100.0), Tolerance);
			TestEqual(*(What + TEXT(" hit radius (cm)")), Joint.HitRadius, float((*Want)->GetNumberField(TEXT("hit_radius_m")) * 100.0), Tolerance);
			TestTrue(*(What + TEXT(" gravity down")), Joint.GravityDir.Equals(FVector(0, 0, -1), Tolerance));
		}
	}

	// vrm1_minimal: the spine collider's extended shape (inside sphere, 0.3 m) replaces its base sphere.
	FVRMSpringConfig Config1;
	FString Error;
	if (VRM::ParseSpringBonesFromFile(FPaths::Combine(Dir, TEXT("vrm1_minimal.vrm")), Config1, Error)
		&& TestEqual(TEXT("vrm1_minimal colliders"), Config1.Colliders.Num(), 2)
		&& TestEqual(TEXT("Extended collider has one sphere"), Config1.Colliders[1].Spheres.Num(), 1))
	{
		TestEqual(TEXT("Extended collider radius (cm)"), Config1.Colliders[1].Spheres[0].Radius, 30.f, Tolerance);
		TestTrue(TEXT("Extended collider is inside"), Config1.Colliders[1].Spheres[0].bInside);
	}
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FVRMFixturesSpringChains, "VRM.Fixtures.SpringChains",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FVRMFixturesSpringChains::RunTest(const FString& Parameters)
{
	// Chains must match the sidecar's springs.chains[].joint_nodes. vrm0_minimal lists only the chain
	// root, so its descendants have to be added (P1.12). Every joint must be a named node (a bone), and
	// the file overload must report the node hierarchy.
	const FString Dir = VRMFixtures::GetFixtureDir();
	const TCHAR* const SpringFixtures[] = { TEXT("vrm0_minimal"), TEXT("vrm1_minimal") };
	for (const TCHAR* Name : SpringFixtures)
	{
		FVRMSpringConfig Config;
		TMap<int32, FName> NodeNames;
		TMap<int32, int32> NodeParent;
		TMap<int32, FVRMNodeChildren> NodeChildren;
		FString Error;
		FString ExpectedText;
		TSharedPtr<FJsonObject> Expected;
		if (!TestTrue(FString::Printf(TEXT("%s parses"), Name),
				VRM::ParseSpringBonesFromFile(FPaths::Combine(Dir, FString(Name) + TEXT(".vrm")), Config, NodeNames, NodeParent, NodeChildren, Error))
			|| !TestTrue(FString::Printf(TEXT("%s sidecar loads"), Name),
				FFileHelper::LoadFileToString(ExpectedText, *FPaths::Combine(Dir, FString(Name) + TEXT(".expected.json")))
				&& FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(ExpectedText), Expected) && Expected.IsValid()))
		{
			continue;
		}

		const TSharedPtr<FJsonObject>* Springs = nullptr;
		const TArray<TSharedPtr<FJsonValue>>* Chains = nullptr;
		if (!TestTrue(TEXT("Sidecar has springs.chains"), Expected->TryGetObjectField(TEXT("springs"), Springs) && Springs
			&& (*Springs)->TryGetArrayField(TEXT("chains"), Chains) && Chains))
		{
			continue;
		}
		if (!TestEqual(FString::Printf(TEXT("%s chain count"), Name), Config.Springs.Num(), Chains->Num()))
		{
			continue;
		}

		auto Join = [](const TArray<int32>& A) { return FString::JoinBy(A, TEXT(","), [](int32 V) { return FString::FromInt(V); }); };
		for (int32 ChainIndex = 0; ChainIndex < Chains->Num(); ++ChainIndex)
		{
			TArray<int32> Want;
			const TSharedPtr<FJsonObject>* Chain = nullptr;
			const TArray<TSharedPtr<FJsonValue>>* Nodes = nullptr;
			if ((*Chains)[ChainIndex].IsValid() && (*Chains)[ChainIndex]->TryGetObject(Chain) && Chain
				&& (*Chain)->TryGetArrayField(TEXT("joint_nodes"), Nodes) && Nodes)
			{
				for (const TSharedPtr<FJsonValue>& N : *Nodes) { Want.Add(int32(N->AsNumber())); }
			}

			TArray<int32> Got;
			for (const int32 J : Config.Springs[ChainIndex].JointIndices)
			{
				if (Config.Joints.IsValidIndex(J)) { Got.Add(Config.Joints[J].NodeIndex); }
			}
			TestTrue(FString::Printf(TEXT("%s chain %d: nodes [%s], expected [%s]"), Name, ChainIndex, *Join(Got), *Join(Want)), Got == Want);

			for (int32 i = 1; i < Got.Num(); ++i)
			{
				const int32* Parent = NodeParent.Find(Got[i]);
				TestTrue(FString::Printf(TEXT("%s: node %d's parent is %d"), Name, Got[i], Got[i - 1]), Parent && *Parent == Got[i - 1]);
			}
		}

		for (const FVRMSpringJoint& Joint : Config.Joints)
		{
			TestTrue(FString::Printf(TEXT("%s: joint node %d is a named bone"), Name, Joint.NodeIndex), NodeNames.Contains(Joint.NodeIndex));
		}
	}
	return true;
}

#endif // WITH_DEV_AUTOMATION_TESTS
