// Copyright (c) 2026 Lifelike & Believable Animation Design, Inc. | Athomas Goldberg. All Rights Reserved.
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS

#include "Interfaces/IPluginManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "VRMSpringBonesParser.h"
#include "VRMSpringBonesTypes.h"

namespace VRMFixtures
{
	/** Plugins/VRMInterchange/Tests/Fixtures (generated by scripts/make_vrm_fixtures.py). */
	static FString GetFixtureDir()
	{
		const TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("VRMInterchange"));
		return Plugin.IsValid() ? FPaths::Combine(Plugin->GetBaseDir(), TEXT("Tests"), TEXT("Fixtures")) : FString();
	}

	static const TCHAR* const Names[] = {
		TEXT("vrm0_minimal"),
		TEXT("vrm1_minimal"),
		TEXT("multi_skin"),
		TEXT("rigid_accessory"),
		TEXT("unnamed_and_duplicate_nodes"),
		TEXT("armature_transform"),
	};
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FVRMFixturesAvailable, "VRM.Fixtures.Available",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FVRMFixturesAvailable::RunTest(const FString& Parameters)
{
	const FString Dir = VRMFixtures::GetFixtureDir();
	if (!TestFalse(TEXT("VRMInterchange plugin found"), Dir.IsEmpty()))
	{
		return false;
	}

	for (const TCHAR* Name : VRMFixtures::Names)
	{
		const FString VrmPath = FPaths::Combine(Dir, FString(Name) + TEXT(".vrm"));
		const FString ExpectedPath = FPaths::Combine(Dir, FString(Name) + TEXT(".expected.json"));
		TestTrue(FString::Printf(TEXT("%s.vrm exists"), Name), FPaths::FileExists(VrmPath));

		FString ExpectedText;
		TSharedPtr<FJsonObject> Expected;
		const bool bLoaded = FFileHelper::LoadFileToString(ExpectedText, *ExpectedPath)
			&& FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(ExpectedText), Expected)
			&& Expected.IsValid();
		TestTrue(FString::Printf(TEXT("%s.expected.json loads"), Name), bLoaded);
	}
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FVRMFixturesSpringSpecDetected, "VRM.Fixtures.SpringSpecDetected",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FVRMFixturesSpringSpecDetected::RunTest(const FString& Parameters)
{
	const FString Dir = VRMFixtures::GetFixtureDir();

	FVRMSpringConfig Config0;
	FString Error;
	TestTrue(TEXT("vrm0_minimal spring data parses"),
		VRM::ParseSpringBonesFromFile(FPaths::Combine(Dir, TEXT("vrm0_minimal.vrm")), Config0, Error));
	TestEqual(TEXT("vrm0_minimal detected as VRM 0.x"), Config0.Spec, EVRMSpringSpec::VRM0);

	FVRMSpringConfig Config1;
	TestTrue(TEXT("vrm1_minimal spring data parses"),
		VRM::ParseSpringBonesFromFile(FPaths::Combine(Dir, TEXT("vrm1_minimal.vrm")), Config1, Error));
	TestEqual(TEXT("vrm1_minimal detected as VRM 1.0"), Config1.Spec, EVRMSpringSpec::VRM1);
	TestEqual(TEXT("vrm1_minimal has one spring"), Config1.Springs.Num(), 1);
	return true;
}

#endif // WITH_DEV_AUTOMATION_TESTS
